### ISSUE TITLE
Actor dnf_package_download unexpectedly terminated

### ISSUE THREAD

**Issue by sejohlun** [AlmaLinux/leapp-repository#15]
**Actual behavior**
The migration from CentOS 7 to Rocky Linux 8 fails with error:

```
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Process Process-476:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/dnfpackagedownload/actor.py", line 51, in process
    xfs_info=xfs_info, storage_info=storage_info, plugin_info=plugin_info, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 385, in perform_rpm_download
    test=True, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 219, in _transaction
    e.stdout = e.stdout.encode('utf-8', 'xmlcharrefreplace')
AttributeError: can't set attribute

======================================================================================
[leapp-logs.tar.gz](https://github.com/AlmaLinux/leapp-repository/files/9762215/leapp-logs.tar.gz) with exit code: 1 - Please check the above details
```
======================================================================================

**To Reproduce**
install 'leapp'
run 'leapp upgrade --debug'
See error

**Expected behavior**
Successful migration

**System information (please complete the following information):**
CentOS Linux release 7.9.2009 (Core)
Linux op5.vallentuna.local 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
leapp-0.14.0-1.el7.noarch
leapp-deps-0.14.0-1.el7.noarch
leapp-data-rocky-0.1-6.el7.noarch
leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.noarch
leapp-upgrade-el7toel8-deps-0.16.0-6.el7.elevate.noarch

Attach (or provide link to) log files if applicable (optional - may contain confidential information):

All logs attached...

**Comment by andrewlukoshko** [comment]
Let's try to all EPEL support to your configuration.
Create the following files in **/etc/leapp/files/vendors.d/:**

epel_map.json
```
{
    "datetime": "202204020934Z",
    "version_format": "1.0.0",
    "mapping": [
        {
            "source_major_version": "7",
            "target_major_version": "8",
            "entries": [
                {
                    "source": "epel",
                    "target": [
                        "epel"
                    ]
                }
            ]
        }
    ],
    "repositories": [
        {
            "pesid": "epel",
            "entries": [
                {
                    "arch": "x86_64",
                    "repoid": "epel",
                    "channel": "ga",
                    "repo_type": "rpm",
                    "major_version": "8"
                },
                {
                    "arch": "x86_64",
                    "repoid": "epel",
                    "channel": "ga",
                    "repo_type": "rpm",
                    "major_version": "7"
                }
            ]
        }
    ]
}
```

epel_pes.json
```
{
    "legal_notice": "Copyright (c) 2022 AlmaLinux OS Foundation",
    "packageinfo": [],
    "timestamp": "202207130941Z"
}
```

epel.repo
```
[epel]
name=Extra Packages for Enterprise Linux 8 - $basearch
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch
enabled=1
gpgcheck=1
countme=1
gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
```

epel.sigs
```
24c6a8a7f4a80eb5
6a2faea2352c64e5
```

Then do as usual:
```
leapp preuprade
leapp upgrade
```

**Comment by sejohlun** [comment]
Same result:
`
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Process Process-476:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/dnfpackagedownload/actor.py", line 51, in process
    xfs_info=xfs_info, storage_info=storage_info, plugin_info=plugin_info, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 385, in perform_rpm_download
    test=True, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 219, in _transaction
    e.stdout = e.stdout.encode('utf-8', 'xmlcharrefreplace')
AttributeError: can't set attribute


==================================================================================
Actor dnf_package_download unexpectedly terminated with exit code: 1 - Please check the above details
==================================================================================

**Comment by sejohlun** [comment]
Same result:
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Process Process-476:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/dnfpackagedownload/actor.py", line 51, in process
    xfs_info=xfs_info, storage_info=storage_info, plugin_info=plugin_info, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 385, in perform_rpm_download
    test=True, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 219, in _transaction
    e.stdout = e.stdout.encode('utf-8', 'xmlcharrefreplace')
AttributeError: can't set attribute


==================================================================================
Actor dnf_package_download unexpectedly terminated with exit code: 1 - Please check the above details
==================================================================================

**Comment by trpl7** [comment]
Same problem trying to upgrade from CentOS 7 to AlmaLinux 8 using elevate-cpanel

Process Process-476:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/dnfpackagedownload/actor.py", line 51, in process
    xfs_info=xfs_info, storage_info=storage_info, plugin_info=plugin_info, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 385, in perform_rpm_download
    test=True, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 219, in _transaction
    e.stdout = e.stdout.encode('utf-8', 'xmlcharrefreplace')
AttributeError: can't set attribute
=====================================================================================================
Actor dnf_package_download unexpectedly terminated with exit code: 1 - Please check the above details
=====================================================================================================

**Comment by MarcelRei** [comment]
I get the same error trying to upgrade from CentOS7 to Rocky.
I tried the above mentioned fix but that didn't help.

**Comment by kludgeaudio** [comment]
Same problem here on six different machines, but another four machines with similar configurations are fine.  Removing all epel packages (and all systems have one or two) and then re-running leapp upgrade does not help.  Any idea at all what is going on or if there is any kind of upgrade?  In our case it appears to have done all the downloads before this happens so if we could just bypass the rest of the module and go to the next one we might even be okay.

**Comment by zaheerabbas1988** [comment]
> Same result: Running transaction check Transaction check succeeded. Running transaction test The downloaded packages were saved in cache until the next successful transaction. You can remove cached packages by executing 'dnf clean packages'. Process Process-476: Traceback (most recent call last): File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap self.run() File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run self._target(*self._args, **self._kwargs) File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run actor_instance.run(*args, **kwargs) File "/usr/lib/python2.7/site-packages/leapp/actors/**init**.py", line 290, in run self.process(*args) File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/dnfpackagedownload/actor.py", line 51, in process xfs_info=xfs_info, storage_info=storage_info, plugin_info=plugin_info, on_aws=on_aws File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 385, in perform_rpm_download test=True, on_aws=on_aws File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 219, in _transaction e.stdout = e.stdout.encode('utf-8', 'xmlcharrefreplace') AttributeError: can't set attribute
> 
> # ==================================================================================
> Actor dnf_package_download unexpectedly terminated with exit code: 1 - Please check the above details

The issue might be with the old python installation. Try removing python2* and python3* packages and then try again.

**Comment by tjyang** [comment]
Once I updated the leapp to latest 0.14 I have same issue on centos 7.9.
- With older 0.12 version elevate, I don't see this dnf_package_download actor issue.
<details>
root@centos7t01 ~]# rpm -qa |grep leapp
leapp-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
python2-leapp-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
leapp-deps-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
leapp-upgrade-el7toel8-0.14.0-100.202109271224Z.b7ebfca.master.el7.elevate.noarch
leapp-data-rocky-0.1-4.el7.noarch
leapp-upgrade-el7toel8-deps-0.14.0-100.202109271224Z.b7ebfca.master.el7.elevate.noarch
[root@centos7t01 ~]#
</details>
- But the older version, I see "more space is needed on the / filesystem"

```
  installing package nss-softokn-freebl-3.79.0-10.el8_6.i686 needs 2728MB on the / filesystem
  installing package nss-softokn-freebl-3.79.0-10.el8_6.i686 needs 4913 inodes on the / filesystem

Error Summary
-------------
Disk Requirements:
   At least 2748MB more space needed on the / filesystem.



============================================================
                       END OF ERRORS
============================================================


Debug output written to /var/log/leapp/leapp-upgrade.log

```
![image](https://user-images.githubusercontent.com/378638/204097391-610a70de-4114-4951-a8de-040679e7c81f.png)

- end

**Comment by MarcelRei** [comment]
My issue was related to "disk space" so I increased the size 
export LEAPP_OVL_SIZE=3000

and the other one was related to an openssl lib which was only el7 and I had to remove first.

**Comment by tjyang** [comment]
> My issue was related to "disk space" so I increased the size export LEAPP_OVL_SIZE=3000
> 
> and the other one was related to an openssl lib which was only el7 and I had to remove first.

@MarcelRei , what version of leapp were you using when ran into disk pace issue ? 
0.12 or 0.14 ?

**Comment by tjyang** [comment]
I create a centos 7.9 VMWare VM from  CentOS-7-x86_64-Minimal-2009 with no extra software installation beside leapp*. 
And leapp upgrade passed, I got a RL8.7. This is good that I know 0.14 leapp is OK.

```
[me@centos7t02 ~]$ rpm -qa |grep leapp
leapp-data-rocky-0.1-6.el7.noarch
python2-leapp-0.14.0-1.el7.noarch
leapp-0.14.0-1.el7.noarch
leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.1.noarch
leapp-repository-deps-el8-5.0.8-100.202203181036Z.249925a3.master.el8.noarch
leapp-deps-el8-5.0.8-100.202203181036Z.249925a3.master.el8.noarch
[me@centos7t02 ~]$ cat /etc/redhat-release ;date
Rocky Linux release 8.7 (Green Obsidian)
Sat Nov 26 12:40:43 CST 2022
[me@centos7t02 ~]$ df -lh
Filesystem               Size  Used Avail Use% Mounted on
devtmpfs                 3.8G     0  3.8G   0% /dev
tmpfs                    3.8G     0  3.8G   0% /dev/shm
tmpfs                    3.8G  856K  3.8G   1% /run
tmpfs                    3.8G     0  3.8G   0% /sys/fs/cgroup
/dev/mapper/centos-root   35G  2.4G   33G   7% /
/dev/sda1               1014M  222M  793M  22% /boot
tmpfs                    777M     0  777M   0% /run/user/1000
[me@centos7t02 ~]$


```

**Comment by MarcelRei** [comment]
> > My issue was related to "disk space" so I increased the size export LEAPP_OVL_SIZE=3000
> > and the other one was related to an openssl lib which was only el7 and I had to remove first.
> 
> @MarcelRei , what version of leapp were you using when ran into disk pace issue ? 0.12 or 0.14 ?

I was using leapp 0.14 but still ran into the issue mentioned above. I just checked the logs better to find the issue.

**Comment by tjyang** [comment]
> > > My issue was related to "disk space" so I increased the size export LEAPP_OVL_SIZE=3000
> > > and the other one was related to an openssl lib which was only el7 and I had to remove first.
> > 
> > 
> > @MarcelRei , what version of leapp were you using when ran into disk pace issue ? 0.12 or 0.14 ?
> 
> I was using leapp 0.14 but still ran into the issue mentioned above. I just checked the logs better to find the issue.

disk space issue still exists in 0.14 version. Thanks for this infomation.

**Comment by kludgeaudio** [comment]
What is happening here is that the error handler is crashing and that is the message that we are seeing.  So there could be all kinds of different errors occurring but we see the same error message for all of them.

I have found that a workaround is to look at /var/log/leapp/leapp-upgrade.log, or for preupgrade, the leapp-preupgrade.log.  Start at the bottom, go from the syntax error up through all of the dismount and cleanup stuff and you will, maybe 50 lines from the end, find some kind of actual error message.  It is sometimes hidden but it's likely to be there.

And yes, if you have an xfs filesystem, you need to increase LEAPP_OVL_SIZE.  I have found I have needed to crank it up as high as 8192 on some systems with large xfs arrays.

But the real problem of the error handler crashing really needs to be addressed by the developers.
--scott
________________________________
From: T.J. Yang ***@***.***>
Sent: Monday, November 28, 2022 6:21 AM
To: AlmaLinux/leapp-repository ***@***.***>
Cc: Dorsey, Scott B. (LARC-D316)[AEGIS] ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [AlmaLinux/leapp-repository] Actor dnf_package_download unexpectedly terminated (Issue #15)


My issue was related to "disk space" so I increased the size export LEAPP_OVL_SIZE=3000
and the other one was related to an openssl lib which was only el7 and I had to remove first.

@MarcelRei<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarcelRei&data=05%7C01%7Cscott.b.dorsey%40nasa.gov%7C17592b304c6d4fb8ab4e08dad132a824%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638052312757900245%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1eah2TkFdtJVVSbh4oVSqlrycEX6mH9ZCkDH6lBo6Ns%3D&reserved=0> , what version of leapp were you using when ran into disk pace issue ? 0.12 or 0.14 ?

I was using leapp 0.14 but still ran into the issue mentioned above. I just checked the logs better to find the issue.

disk space issue still exists in 0.14 version. Thanks for this infomation.

**Comment by vwbusguy** [comment]
> Try removing python2* and python3* packages and then try again.

This ended up being my issue.  



> I have found that a workaround is to look at /var/log/leapp/leapp-upgrade.log, or for preupgrade, the leapp-preupgrade.log. Start at the bottom, go from the syntax error up through all of the dismount and cleanup stuff and you will, maybe 50 lines from the end, find some kind of actual error message. It is sometimes hidden but it's likely to be there.

Thanks!  This is how I found out what the exact issue was.  Turned out to be a python library incompatibility and it was buried in that log file.

**Comment by tjyang** [comment]
My understanding so far for solution.
- workaround: to avoid crashing the error handler, remove pkg conflicts in advance.
- Fix the error handler.

**Comment by vwbusguy** [comment]
> * remove pkg conflicts in advance

I'm curious if the logic of `dnf system-upgrade download` could possibly help here.  Or at least showing the package conflict errors in stderr rather than buried in the log file.

**Comment by danFbach** [comment]
> > * remove pkg conflicts in advance
> 
> I'm curious if the logic of `dnf system-upgrade download` could possibly help here. Or at least showing the package conflict errors in stderr rather than buried in the log file.

I would agree with this. If package conflicts _can_ be removed automatically, remove them. If not, at least better inform the user. I, and others, have encountered this issue, that were all resolved by removing conflicting packages.
The common **reported** error seems to be:
```
Risk Factor: high
Title: Packages from unknown repositories may not be installed
Summary: 1 packages may not be installed or upgraded due to repositories unknown to leapp:
- kernel-uek (repoid: ol8-uek)
```
However, no information is given immediately to the user that this occurred because of conflicting packages, and one must dig into leapp-upgrade.log in order to find the information. For me and many others, it was python conflicts, but i've seen it occur with other packages.

**Comment by kludgeaudio** [comment]
There are many things which can fail in the upgrade process.  I have had all kinds of different errors, including package conflicts but also simple things like not having LEAPP_OVL_SIZE set.  If you have shotwell installed, it gets confused because it wants to replace shotwell with gnome-photos and it can't find gnome-photos.  All kinds of things can go wrong in the process.

The number one problem is that the error handler is broken.  The user often cannot figure out what has gone wrong because the error handler is broken.

It would be good long-term to make fewer things go wrong, but FIRST fix the error handler.
--scott
________________________________
From: Dan Fehrenbach ***@***.***>
Sent: Friday, December 30, 2022 1:38 PM
To: AlmaLinux/leapp-repository ***@***.***>
Cc: Dorsey, Scott B. (LARC-D316)[AEGIS] ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [AlmaLinux/leapp-repository] Actor dnf_package_download unexpectedly terminated (Issue #15)


  *   remove pkg conflicts in advance

I'm curious if the logic of dnf system-upgrade download could possibly help here. Or at least showing the package conflict errors in stderr rather than buried in the log file.

I would agree with this. If package conflicts can be removed automatically, remove them. If not, at least better inform the user. I, and others, have encountered this issue, that were all resolved by removing conflicting packages.
The common reported error seems to be:

Risk Factor: high
Title: Packages from unknown repositories may not be installed
Summary: 1 packages may not be installed or upgraded due to repositories unknown to leapp:
- kernel-uek (repoid: ol8-uek)


However, no information is given immediately to the user that this occurred because of conflicting packages, and one must dig into leapp-upgrade.log in order to find the information. For me and many others, it was python conflicts, but i've seen it occur with other packages.

**Comment by yuravk** [comment]
I am closing this issue due to inactivity. If you are still experiencing this problem, please feel free to reopen this ticket or create a new one.
