### ISSUE TITLE
leapp dnfplugin.py conflicts on salt python3 packages

### ISSUE THREAD

**Issue by atoomic** [AlmaLinux/leapp-repository#30]
Some cPanel customers are reporting this issue while upgrading from CentOS 7 to AlmaLinux 8.
The error seems to come from the `leapp-repository`

This happened on a customer’s server where they removed the salt repository, but not the salt packages causing an error:
```
Process Process-476:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/dnfpackagedownload/actor.py", line 51, in process
    xfs_info=xfs_info, storage_info=storage_info, plugin_info=plugin_info, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 385, in perform_rpm_download
    test=True, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 219, in _transaction
    e.stdout = e.stdout.encode('utf-8', 'xmlcharrefreplace')
AttributeError: can't set attribute{code}
This is due to the conflict:
{code}# grep -A5 'Transaction test error' /var/log/leapp/leapp-upgrade.log
2022-12-08 03:24:30.847 DEBUG    PID: 11736 leapp.workflow.Download.dnf_package_download: Error: Transaction test error:
2022-12-08 03:24:30.849 DEBUG    PID: 11736 leapp.workflow.Download.dnf_package_download:   file /usr/lib/python3.6/site-packages/__pycache__/six.cpython-36.opt-1.pyc from install of python3-six-1.11.0-8.el8.noarch conflicts with file from package python36-six-1.14.0-3.el7.noarch
2022-12-08 03:24:30.850 DEBUG    PID: 11736 leapp.workflow.Download.dnf_package_download:   file /usr/lib/python3.6/site-packages/__pycache__/six.cpython-36.pyc from install of python3-six-1.11.0-8.el8.noarch conflicts with file from package python36-six-1.14.0-3.el7.noarch
2022-12-08 03:24:30.852 DEBUG    PID: 11736 leapp.workflow.Download.dnf_package_download:   file /usr/lib/python3.6/site-packages/six.py from install of python3-six-1.11.0-8.el8.noarch conflicts with file from package python36-six-1.14.0-3.el7.noarch
2022-12-08 03:24:30.853 DEBUG    PID: 11736 leapp.workflow.Download.dnf_package_download:   file /usr/lib/python3.6/site-packages/urllib3/__init__.py from install of python3-urllib3-1.24.2-5.el8.noarch conflicts with file from package python36-urllib3-1.25.6-2.el7.noarch
2022-12-08 03:24:30.854 DEBUG    PID: 11736 leapp.workflow.Download.dnf_package_download:   file /usr/lib/python3.6/site-packages/urllib3/__pycache__/__init__.cpython-36.opt-1.pyc from install of python3-urllib3-1.24.2-5.el8.noarch conflicts with file from package python36-urllib3-1.25.6-2.el7.noarch
```

Caused by salt packages:
```
[03:55:04 sau-41805-vs root@94509955 /var/log/leapp]cPs# yum list installed | grep @salt-py3-latest
libsodium.x86_64                                1.0.18-1.el7           @salt-py3-latest
python3.x86_64                                  3.6.8-18.el7           @salt-py3-latest
python3-libs.x86_64                             3.6.8-18.el7           @salt-py3-latest
python36-PyYAML.x86_64                          3.13-1.el7             @salt-py3-latest
python36-chardet.noarch                         3.0.4-12.el7           @salt-py3-latest
python36-contextvars.noarch                     2.4-1.el7              @salt-py3-latest
python36-idna.noarch                            2.10-1.el7             @salt-py3-latest
python36-immutables.x86_64                      0.14-1.el7             @salt-py3-latest
python36-jinja2.noarch                          2.11.1-1.el7           @salt-py3-latest
python36-m2crypto.x86_64                        0.35.2-5.el7           @salt-py3-latest
python36-markupsafe.x86_64                      0.23-4.el7             @salt-py3-latest
python36-msgpack.x86_64                         0.6.2-2.el7            @salt-py3-latest
python36-psutil.x86_64                          5.6.7-1.el7            @salt-py3-latest
python36-pycurl.x86_64                          7.43.0-8.el7           @salt-py3-latest
python36-pysocks.noarch                         1.6.8-7.el7            @salt-py3-latest
python36-requests.noarch                        2.14.2-2.el7           @salt-py3-latest
python36-urllib3.noarch                         1.25.6-2.el7           @salt-py3-latest
python36-zmq.x86_64                             18.0.1-1.el7           @salt-py3-latest
salt.noarch                                     3005.1-1.el7           @salt-py3-latest
zeromq.x86_64                                   4.1.4-7.el7            @salt-py3-latest
```

Refs: CPANEL-42014

**Comment by tjyang** [comment]
@atoomic , I have same problem. 
My current solution is to remove salt-minion package and disable salt repo first before  running leapp {preupgrade|upgrade}. All the salt-minion config/data can be re-used after salt-minion re-install on new OS.
