### ISSUE TITLE
Issue with leapp upgrade

### ISSUE THREAD

**Issue by SuperSchramm** [AlmaLinux/leapp-repository#53]
This issue appears to be similar to the issue described in issue #15 however, that issue appears to be related to space and I do not have an issue with space on the system in question. I am getting the same message which looks to be related to the subscription-manager but I have removed subscription-manager, and any reference to it, and it is the same message using Oracle Linux or Rocky Linux.

I get the same error regardless of whether I use the --no-rhsm option or not. 

```
Total                                            71 MB/s | 1.2 GB     00:17
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Process Process-476:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/dnfpackagedownload/actor.py", line 51, in process
    xfs_info=xfs_info, storage_info=storage_info, plugin_info=plugin_info, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 385, in perform_rpm_download
    test=True, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 219, in _transaction
    e.stdout = e.stdout.encode('utf-8', 'xmlcharrefreplace')
AttributeError: can't set attribute


=====================================================================================================
Actor dnf_package_download unexpectedly terminated with exit code: 1 - Please check the above details
=====================================================================================================

Debug output written to /var/log/leapp/leapp-upgrade.log

============================================================
                           REPORT
============================================================

A report has been generated at /var/log/leapp/leapp-report.json
A report has been generated at /var/log/leapp/leapp-report.txt

============================================================
                       END OF REPORT
============================================================
```
The leapp-upgrade.log only shows the following:

``` 
2023-02-22 09:01:32.615 DEBUG    PID: 23413 leapp.workflow.Download.dnf_package_download: Command ['systemd-nspawn', '--register=no', '--quiet', '-D', u'/var/lib/leapp/el8userspace', '--setenv=LEAPP_UPGRADE_PATH_TARGET_RELEASE=8.6', '--setenv=LEAPP_NO_RHSM=1', '--setenv=LEAPP_EXPERIMENTAL=0', '--setenv=LEAPP_UPGRADE_PATH_FLAVOUR=default', '--setenv=LEAPP_COMMON_TOOLS=:/etc/leapp/repos.d/system_upgrade/el7toel8/tools', '--setenv=LEAPP_COMMON_FILES=:/etc/leapp/repos.d/system_upgrade/common/files:/etc/leapp/repos.d/system_upgrade/el7toel8/files', '--setenv=LEAPP_IPU_IN_PROGRESS=7to8', '--setenv=LEAPP_UNSUPPORTED=0', '--setenv=LEAPP_EXECUTION_ID=5c09e8eb-0ac9-48d9-9b3a-8d1b0dd3d4d4', '--setenv=LEAPP_HOSTNAME=systemNameRedacted', '/usr/bin/dnf', 'rhel-upgrade', 'download', '/var/lib/leapp/dnf-plugin-data.txt', '--disableplugin', 'subscription-manager'] failed with exit code 1.
2023-02-22 09:01:32.630 DEBUG    PID: 23413 leapp.workflow.Download.dnf_package_download: External command has finished: ['systemd-nspawn', '--register=no', '--quiet', '-D', u'/var/lib/leapp/el8userspace', '--setenv=LEAPP_UPGRADE_PATH_TARGET_RELEASE=8.6', '--setenv=LEAPP_NO_RHSM=1', '--setenv=LEAPP_EXPERIMENTAL=0', '--setenv=LEAPP_UPGRADE_PATH_FLAVOUR=default', '--setenv=LEAPP_COMMON_TOOLS=:/etc/leapp/repos.d/system_upgrade/el7toel8/tools', '--setenv=LEAPP_COMMON_FILES=:/etc/leapp/repos.d/system_upgrade/common/files:/etc/leapp/repos.d/system_upgrade/el7toel8/files', '--setenv=LEAPP_IPU_IN_PROGRESS=7to8', '--setenv=LEAPP_UNSUPPORTED=0', '--setenv=LEAPP_EXECUTION_ID=5c09e8eb-0ac9-48d9-9b3a-8d1b0dd3d4d4', '--setenv=LEAPP_HOSTNAME=systemNameRedacted', '/usr/bin/dnf', 'rhel-upgrade', 'download', '/var/lib/leapp/dnf-plugin-data.txt', '--disableplugin', 'subscription-manager']
```

**Comment by prilr** [comment]
I believe both this and #15 should be displaying the actual message for the error now, and not the `e.stdout = e.stdout.encode('utf-8', 'xmlcharrefreplace')` line.

@andrewlukoshko The encoding change in question change was released, right?

**Comment by yuravk** [comment]
I am closing this issue due to inactivity. If you are still experiencing this problem, please feel free to reopen this ticket or create a new one.
